### ISSUE TITLE
Setup instructions?

### ISSUE THREAD

**Issue by stevensq1** [santanusetu/cmpe239-StockMarketPredictNAnalysis#1]
Hello, Do you mind sharing instructions on how to set this up?

Thank you very much ;)

**Comment by santanusetu** [comment]
Sorry for the late reply. You just need to download the code and run in your system. 
I have used Spring Tool Suite (STS) as IDE. But feel free to use any of the IDE of your choice. 

The dataset for stocks can be found inside the following folder
cmpe239-StockMarketPredictNAnalysis/StockMaketPrediction/data/

You can find all the rest end points in the following file. Feel free to use any of the Rest Clients (like PostMan etc) to test those
cmpe239-StockMarketPredictNAnalysis/StockMaketPrediction/src/main/java/org/stockmaketprediction/controller/StockMarketPredictorRestEndPointProvider.java

For an working demo of the project. Visit the YouTube link:
https://www.youtube.com/watch?v=LJn6nSkCtPA

If you have any specific doubt - feel free to contact me anytime :)

**Comment by santanusetu** [comment]
Also for Twitter Sentiment Analysis of Cashtags - create an developer profile in twitter. Hope the above information will help you to start up. 

Closing the issue. Feel free to open a new one if you are stuck in somewhere.
